# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: prometheus
    storageCapacity: 50Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/prometheus
    server: io.local
    type: free
    reclaimPolicy: Retain
  - name: alertmanager
    storageCapacity: 5Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/prom_alertman
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: mastodon
    storageCapacity: 50Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/mastodon
    server: io.local
    reclaimPolicy: Recycle
    type: free