# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: share_zero
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_zero
    server: io.local
    type: free
    reclaimPolicy: Retain
  - name: share_one
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_one
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: share_two
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_two
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: share_three
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_three
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: share_four
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_four
    server: io.local
    reclaimPolicy: Retain
    type: free


