# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: volume-zeo
    storageCapacity: 10Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/share_zero
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-one
    storageCapacity: 10Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_one
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-two
    storageCapacity: 10Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_two
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-three
    storageCapacity: 10Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_three
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-four
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_four
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-five
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_five
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-six
    storageCapacity: 100Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_six
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-seven
    storageCapacity: 20Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_seven
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-eight
    storageCapacity: 20Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_eight
    server: callisto.local
    reclaimPolicy: Retain
  - name: volume-nine
    storageCapacity: 20Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_nice
    server: callisto.local
    reclaimPolicy: Retain


