# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: prometheus
    storageCapacity: 50Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/prometheus
    server: 192.168.1.37
    type: free
    reclaimPolicy: Retain
  - name: alertmanager
    storageCapacity: 5Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/prom_alertman
    server: 192.168.1.37
    reclaimPolicy: Retain
    type: free
  - name: gitea
    storageCapacity: 50Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/gitea
    server: 192.168.1.37
    reclaimPolicy: Recycle
    type: free
  - name: grafana
    storageCapacity: 5Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/grafana
    server: 192.168.1.37
    reclaimPolicy: Retain
    type: free