# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: prometheus
    storageCapacity: 50Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/prometheus
    server: io.local
    type: free
    reclaimPolicy: Recycle
  - name: alertmanager
    storageCapacity: 50Gi
    accessMode: ReadWriteOnce
    path: /srv/nfs_shares/alertman
    server: io.local
    reclaimPolicy: Recycle
    type: free


localVolumes:
  - name: minio-storage
    storageCapacity: 40Gi
    hostName: sage
    reclaimPolicy: Recycle
    accessMode: ReadWriteOnce
    type: s3
    path: /srv/minio