# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: share-zero
    storageCapacity: 50Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_zero
    server: io.local
    type: free
    reclaimPolicy: Retain
  - name: share-one
    storageCapacity: 50Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_one
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: share-two
    storageCapacity: 50Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_two
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: share-three
    storageCapacity: 50Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_three
    server: io.local
    reclaimPolicy: Retain
    type: free
  - name: share-four
    storageCapacity: 50Gi
    accessMode: ReadWriteMany
    path: /srv/nfs_shares/share_four
    server: io.local
    reclaimPolicy: Retain
    type: free


