# Default values for volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfsVolumes: 
  - name: volume-one
    storageCapacity: 1Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_one
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-two
    storageCapacity: 1Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_two
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-three
    storageCapacity: 1Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_three
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-four
    storageCapacity: 10Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_four
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-five
    storageCapacity: 10Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_five
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-six
    storageCapacity: 10Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_six
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-seven
    storageCapacity: 2Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_seven
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-eight
    storageCapacity: 2Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_eight
    server: callisto.attlocal.net
    reclaimPolicy: Retain
  - name: volume-nine
    storageCapacity: 2Gi
    accessMode: ReadWriteMany
    path: /srv/m/share_nice
    server: callisto.attlocal.net
    reclaimPolicy: Retain


