apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
data:
  master.conf: |
    {{- with .Values.redis }}
    protected-mode {{ .protectedMode }}
    port {{ .port }}
    bind {{ .bind  }}
    tcp-backlog 511
    timeout {{ .timeout }}
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases {{ .databases }}
    dir {{ .dataDirectory }}
    {{- end }}
  slave.conf: |
    slaveof redis-0.redis {{ .port }}