
{{- range $v := .Values.localVolumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $v.name | quote }}
  labels:
    name: {{ $v.name | quote }}
    type: {{ $v.type | quote }}
    storage: local
spec:
  capacity:
    storage: {{ $v.storageCapacity | quote }}
  accessModes:
    - {{ $v.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ $v.reclaimPolicy | quote }}
  storageClassName: local-storage
  local:
    path: {{ $v.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $v.hostName | quote }}
{{- end }}