{{ range $v := .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $v.name | quote }}
  name: admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "adminBinding"
  namespace: {{ $v.name | quote }}
subjects:
    - kind: Group
      name: "{{ $v.name }}Admin" 
      apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: "admin"
  apiGroup: rbac.authorization.k8s.io
{{ end }}