{{ range $v := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $v.name | quote }}
    labels:
        app.kubernetes.io/name: {{ $v.name | quote }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
        chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
        release: {{ $.Release.Name  | quote}}
{{ end }}