{{ range $v := .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $v.name | quote }}
  name: "powerUser"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "configmaps", "deployments"]
  verbs: ["get", "watch", "list", "update", "edit", "exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "powerUserBinding"
  namespace: {{ $v.name | quote }}
subjects:
    - kind: Group
      name: "{{ $v.name }}PowerUser" 
      apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: "powerUser"
  apiGroup: rbac.authorization.k8s.io
{{ end }}