{{ range $v := .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $v.name | quote }}
  name: "readOnly"
rules:
- apiGroups: [""] 
  resources: ["pods", "configmaps", "deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "readOnlyGroup"
  namespace: {{ $v.name | quote }}
subjects:
    - kind: Group
      name: "{{ $v.name }}ReadOnly" 
      apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: "readOnly" 
  apiGroup: rbac.authorization.k8s.io
{{ end }}