apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage-claim
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi