apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.namespace.name | quote }}
type: Opaque
data:
  PASSWORD:  {{ default "password" .Values.user.password | b64enc | quote }}